# Generated by Django 3.0.6 on 2020-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('S', 'Sports'), ('H', 'History'), ('A', 'Art'), ('G', 'Geography')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
