# Generated by Django 3.0.6 on 2020-05-30 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200528_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('21', 'Sports'), ('22', 'Geography'), ('23', 'History'), ('25', 'Art')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='difficulty',
            field=models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], max_length=50),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=500)),
                ('incorrect_answer_1', models.CharField(max_length=500)),
                ('incorrect_answer_2', models.CharField(max_length=500)),
                ('incorrect_answer_3', models.CharField(max_length=500)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
    ]
