# Generated by Django 3.0.6 on 2020-05-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20200530_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
