# Generated by Django 3.0.6 on 2020-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20200530_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer_1',
            new_name='choices1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer_2',
            new_name='choices2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer_3',
            new_name='choices3',
        ),
        migrations.AddField(
            model_name='question',
            name='choices4',
            field=models.CharField(default='dog', max_length=500),
            preserve_default=False,
        ),
    ]
