# Generated by Django 3.0.6 on 2020-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_player',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
