# Generated by Django 3.0.6 on 2020-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_player_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_player',
            name='complete_date',
            field=models.DateField(null=True, verbose_name='complete_date'),
        ),
    ]
