# Generated by Django 3.0.6 on 2020-06-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_player_complete_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament_player',
            old_name='highscore',
            new_name='score',
        ),
    ]
