# Generated by Django 3.0.6 on 2020-06-06 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0009_auto_20200604_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament_Player',
            new_name='TournamentPlayer',
        ),
    ]
